thespotnet/config/routes.rb
TheSpotNet::Application.routes.draw do	
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :users
    resources :properties
    resources :work_orders
    resources :inventories
    resources :lost_founds
    
    resources :messages do
      collection do
        get 'inbox'
      end
    end

    #resources :cleaners
    get 'cleaners_list'                   => 'cleaners#cleaners_list'
    delete 'cleaner/:id'                      => 'cleaners#delete_cleaner', as: 'delete_cleaner'

    post 'update_cleaners'                => 'cleaners#update_cleaners'
    get 'time_clocks'                     => 'cleaners#time_clocks'
    get 'management'                      => 'cleaners#management'    
  end
  
  mount API => '/'

  devise_for :users, controllers: {sessions: "sessions"}
  root :to => 'home#index'
  
  post 'api/v1/accounts/sign_in'        => 'home#create_session'
  post 'api/v1/accounts/sign_out'       => 'home#delete_session'
  
end

thespotnet/app/models/inventory.rb
class Inventory
  include Mongoid::Document
  include Mongoid::Timestamps
  

  PRICING_TYPES = %w[% $ $$]

  field :ivt_id,                type: String
  field :name,                  type: String
  field :re_order_point,        type: String
  field :quantity,              type: Integer, default: 0
  field :purchase_date,         type: Date
  field :location,              type: String

  field :cost,                  type: Float
  field :price_type,            type: String

  field :notes,                 type: String
  
  belongs_to :member, class_name: "User"
  belongs_to :user
  belongs_to :property

  validates_presence_of :ivt_id, :name, :location, :cost, :price_type

  def self.search(search)
    if search.present?
      self.or({ :ivt_id => /.*#{search}*./ }, { :name => /.*#{search}*./ })
    else
      self
    end
  end

  def selling_price
    case price_type
    when Inventory::PRICING_TYPES[0]
      (cost / 100.0) + 100
    when Inventory::PRICING_TYPES[1]
      cost + 15
    when Inventory::PRICING_TYPES[2]
      cost
    end
  end

  def self.itv_list
    ivt_list = self.all.map(&:ivt_id).uniq
  end

  def self.count(ivt_id)
    inventories = self.where(ivt_id:ivt_id)
    inventories.map(&:quantity).sum
  end
end

thespotnet/app/controllers/admin/inventories_controller.rb
class Admin::InventoriesController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin
  def index
    @inventories = current_user.is_admin? ? Inventory.all : current_user.inventories
    if params[:search].present?
      @inventories = @inventories.search(params[:search]) #.paginate(page: params[:page], :per_page => 10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def new
    @inventory = Inventory.new
  end

  def create
    purchase_date = params[:inventory][:purchase_date]
    if purchase_date.present? 
      dt = DateTime.strptime(purchase_date, "%m/%d/%Y")
      params[:inventory][:purchase_date] = dt.strftime("%Y-%m-%d")
    end

    @inventory = current_user.inventories.build(params[:inventory].permit(:ivt_id, :name, :re_order_point, :quantity, :purchase_date, :location, :cost, :price_type, :notes));
    respond_to do |format|
      if @inventory.save
        format.html { redirect_to action: :index}
        format.json { render json: @inventory, status: :created, location: @inventory}
        flash[:notice] = 'New Inventory was created successfully'
      else
        format.html { render action: :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end      
    end
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end
  def update
    @inventory = Inventory.find(params[:id])
  end
  
  def destroy
    @inventory = Inventory.find(params[:id])
  end  
end

thespotnet/app/views/admin/inventories/_form.html.haml
.row  
  = simple_form_for([:admin, @inventory], :html=> {class: 'form-horizontal', multipart: true, :"data-validate" => "parsley"}) do |f|
    = f.error_notification
    .form-inputs
      .general
        %fieldset.group-border
          %legend.group-border General
          %br/
          .row
            .span4
              = f.input :ivt_id, required: true, label: "SKU", :"data-required"=>"true"
              = f.input :name, required: true
              = f.input :re_order_point, label: "Re-Order Point"
            .span4.offset1              
              = f.input :quantity
              = f.input :purchase_date, input_html:{:"data-behaviour"=>'datepicker'}
              = f.input :location
      .pricing-options
        %fieldset.group-border
          %legend.group-border Pricing Options
          %br/
          .row
            .span4
              %br/
              = text_field_tag :cost, f.object.cost.present? ? f.object.cost : '', name: "inventory[cost]"
              %br/
              %br/
              = select_tag :price_type, options_for_select(Inventory::PRICING_TYPES), name: "inventory[price_type]"
              %br/
              %br/
            .span4
              .pricing-style-box{style:'background-color: #ff9900;'}
                %br/
                %br/
                %br/
            .span3
              %label{style:'text-align:center;'} COST PER ITEM
              %br/
              %label#price_label{style:'font-size: 50px;text-align: center;'}

      .note-info
        %fieldset.group-border
          %legend.group-border Notes
          %br/
          .row
            =f.input :notes, as: :text, label: false, input_html:{cols:80, rows:5, class: 'span10'}
    .form-actions
      = f.button :submit, "Submit", class: 'btn btn-primary offset2'
      = link_to "Cancel", admin_inventories_path, class: 'btn btn-default offset1'


:javascript
  $("#cost").change(function(){
    if($("#price_type").val()=="%"){
      cost = (parseInt($("#cost").val()) / 100 *100) + 100
      $("#price_label").text("$"+cost)
    }else if($("#price_type").val()=="$"){
      cost = (parseInt($("#cost").val()) + 15)
      $("#price_label").text("$"+cost)
    }else if($("#price_type").val()=="$$"){
      cost = parseInt($("#cost").val())
      $("#price_label").text("$"+cost)
    }   

  });

  $("#price_type").change(function(){
    if($(this).val()=="%"){
      cost = (parseInt($("#cost").val()) / 100 *100) + 100
      $("#price_label").text("$"+cost)
      $(".pricing-style-box").css("background-color", "#ff9900")
    }else if($(this).val()=="$"){
      cost = (parseInt($("#cost").val()) + 15)
      $("#price_label").text("$"+cost)
      $(".pricing-style-box").css("background-color", "#2b78e4")
    }else if($(this).val()=="$$"){
      cost = parseInt($("#cost").val())
      $("#price_label").text("$"+cost)
      $(".pricing-style-box").css("background-color", "#351c75")
    }
  });

thespotnet/app/views/admin/inventories/edit.html.haml
.container
  .row.header-row{style:'border-bottom: 1px solid #000000; margin-bottom:20px;'}
    .span8{style:'margin-left: 0px;'}
      %h3{style:'margin-bottom: 0px;'} Edit Inventory
    
    .span1.pull-right
  = render "form"

thespotnet/app/views/admin/inventories/index.html.haml
.row.first-row
  .span7
    %h3 Inventory Overview
  .span3{style:'margin-top:20px;'}
    = form_tag admin_inventories_path, method: 'get', :class=>'form-search', :id=>'inventory_search_form'
    .input.input-prepend{style:'width:80%;'}
      %button{type:'submit',class:'btn'} 
        %i.icon-search{:onclick=>'javascript:$("#inventory_search_form").submit()',style:'margin-top:2px;'}
      = text_field_tag 'search', params[:search], :class=>'span3 search-query', style:'padding-left:5px;padding-right:5px;width:100%;'
      %span.fornav-end
        %i.icon-remove-sign{:onclick=>'javascript:$("#inventory_search_form .search-query").val(""); $("#inventory_search_form").submit()', style:'margin-left: -20px;margin-top: -6px;position: relative;'}
      
  .span2{style:'margin-top:20px;'}
    = link_to "New Inventory", new_admin_inventory_path, class: 'btn btn-primary pull-right', :"data-no-turbolink"=>true
.row.customers-contents
  %table.table.table-striped.table-hover.table-bordered
    %thead
      %tr
        %th SKU
        %th Name
        %th Purchaased Cost
        %th Selling Price
        %th Quantity
        %th Re-Order Point
        %th Last Purchase Date
        %th Manage
    %tbody
      - @inventories.each do |inventory|
        %tr
          %td= inventory.ivt_id
          %td= inventory.name
          %td= inventory.cost
          %td= inventory.selling_price
          %td= inventory.quantity
          %td= inventory.re_order_point
          %td= inventory.purchase_date.strftime("%m/%d/%Y")
          %td
            = link_to(edit_admin_inventory_path(inventory), class: 'btn btn-mini', :"data-no-turbolink"=>true) do
              %i.icon-pencil

            = link_to(admin_inventory_path(inventory), class: 'btn btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
              %i.icon-trash
    %tfoot
      

thespotnet/app/views/admin/inventories/new.html.haml
.new-inventory-page
  .row.header-row{style:'border-bottom: 1px solid #000000; margin-bottom:20px;'}
    .span8{style:'margin-left: 0px;'}
      %h3{style:'margin-bottom: 0px;'} Create New Inventory
    
    .span1.pull-right
  = render "form"