obi-frontend-mobile-page/config/routes.rb
ObiJob::Application.routes.draw do

  get "mobile_page/oneday", :as => "oneday"
  get "mobile_page/onemonth", :as => "onemonth"
  get "mobile_page/fourday", :as => "fourday"

  get "mobile_page/index", :as => "mobile_home"

  get "static_pages/home", :as=> "home"

  get "static_pages/findgym", :as =>"findgym"

  get "static_pages/checkout", :as => "checkout"
  get "static_pages/gymaccount", :as => "gymaccount"

  get "static_pages/choosepass", :as => "choosepass"
  get "static_pages/returninguser", :as => "returninguser"
  get "static_pages/index", :as => "index"

  get "static_pages/workout", :as => "go_work_out"

  resources :posts
  get "mypasses/mypasses", :as =>"mypasses"
  get "mypasses/myaccount", :as => "myaccount"
  get "mypasses/tabtest"

  root :to => 'mobile_page#index'

end

obi-frontend-mobile-page/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :image, :name, :title
end

obi-frontend-mobile-page/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

obi-frontend-mobile-page/app/controllers/mobile_page_controller.rb
class MobilePageController < ApplicationController
  def oneday
  end

  def onemonth
  end

  def fourday
  end
end

obi-frontend-mobile-page/app/controllers/mypasses_controller.rb
class MypassesController < ApplicationController
  def mypasses
  end
  def tabtest
  end
  def myaccount

  end
end

obi-frontend-mobile-page/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

obi-frontend-mobile-page/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def findgym
  end

  def checkout
  end

  def workout
  end
  def choosepass
  end
  def returninguser
  end
  def gymaccount
  end
end

obi-frontend-mobile-page/app/helpers/application_helper.rb
module ApplicationHelper
end

obi-frontend-mobile-page/app/helpers/mobile_page_helper.rb
module MobilePageHelper
end

obi-frontend-mobile-page/app/helpers/mypasses_helper.rb
module MypassesHelper
end

obi-frontend-mobile-page/app/helpers/posts_helper.rb
module PostsHelper
end

obi-frontend-mobile-page/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

obi-frontend-mobile-page/app/views/mypasses/myaccount.html.haml
.row.account-info
  %p.page-title MY ACCOUNT
  .row.account-box
    .row
      %p.container-title ACCOUNT INFO
    .span13.control-box
      .span4
        .control-group
          .controls
            %input#first-name{:placeholder => "Jogn", :type => "text"}/
        .control-group
          .controls
            %input#password{:placeholder => "********", :type => "password"}/
      .span4
        .control-group
          .controls
            %input#last-name{:placeholder => "Doe", :type => "text"}
        .control-group
          .controls
            %input#password-confirm{:placeholder => "********", :type => "password"}
      .span4
        .control-group
          .controls
            %input#email-address{ :placeholder => "jdoe@email.com", :type => "email" }
  .row.account-box
    .row
      %p.container-title BILLING ADDRESS
    .span13.control-box.billing-control-box
      .span8
        .control-group
          .controls
            %input#street-name{:placeholder => "123 Street", :type => "text"}/
        .control-group
          .controls
            %input#apt-field{:placeholder => "Apt 00", :type => "text"}/
      .span4
        .control-group
          .row
            .span2
              %input#first-name{:placeholder => "City", :type => "text"}/
            .span1
              %select.filter_select.span2{:style=>""}
                %option
                  ST
                %option
                  TS
        .control-group
          .controls
            %input#number-field{:placeholder => "12345", :type => "text"}
  .row.account-box
    .row
      %p.container-title CREDIT CARD INFO
    .span13.control-box.credit-card-info-box
      .span8
        .control-group
          .controls
            %input#full-name{:placeholder => "John Doe", :type => "text"}/
        .control-group
          .controls
            %input#phone-number{:placeholder => "**** **** **** 3182", :type => "text"}/
      .span4
        .control-group
          .row
            .span2
              %label EXP. DATE
            .span1
              %select.filter_select.span2{:style=>""}
                %option
                  00
                %option
                  10
            .span1{:style=>"width:10px;"}
              %label{:style => "width:10px"} /
            .span1
              %select.filter_select.span2{:style=>""}
                %option
                  00
                %option
                  10
        .control-group
          .controls
            %input#cvv-field{:placeholder => "cvv", :type => "text"}
  .row.account-info-box-controls
    .span3.offset5
      %button.btn{:type => "button"} CANCEL
    .span3
      %button.btn.btn-success{:type => "button"} SAVE

obi-frontend-mobile-page/app/views/mypasses/mypasses.html.haml
.container
  .row.passes-page
    .row
      %br/
      %br/
      %p.page_title MY PASSES
      %br/
      %br/
    .row.tab-content
      %ul
        %li
          %a.btn.selected{:href=>'#tab1'} CURRENT
        %li
          %a.btn{:href=>'#tab2'} EXPIRED
      .controls.controls-row
        .filter_by
          %label.span1{:style=>"font-size:10px;padding:0px 2px 0px 2px;"} FILTER BY
          %select.filter_select.span2{:style=>""}
            %option
              IN USE
            %option
              Status
      #tab1
        %table{:cellspacing=>'0'}
          %tr
            %th
              .label STATUS
            %th
              .label TYPE OF PASS
            %th
              .label GYM NAME/LOCATION
            %th
              .label DATE PURCHASED
            %th
              .label DATE ACTIVATED
            %th
              .label DATE EXPIRED
            %th
              .label REDEEM CODE
          %tr
            %td In Use
            %td 4-day
            %td David Barton NY, NY
            %td 1/29/13
            %td 1/31/13
            %td 3/4/13
            %td UNX82L
          %tr
            %td Not Activated
            %td 1-day
            %td Crunch LA, CA
            %td 1/29/13
            %td ...
            %td 3/1/13
            %td ZJ1T78
          %tr
            %td Not Activated
            %td 1-day
            %td 24 Hr Fitness SF, CA
            %td 1/29/13
            %td ...
            %td 3/1/13
            %td 92KBW8

      #tab2
        %table{:cellspacing=>'0'}
          %tr
            %th
              .label STATUS
            %th
              .label TYPE OF PASS
            %th
              .label GYM NAME/LOCATION
            %th
              .label DATE PURCHASED
            %th
              .label DATE ACTIVATED
            %th
              .label DATE EXPIRED
            %th
              .label REDEEM CODE
          %tr
            %td In Use
            %td 4-day
            %td David Barton NY, NY
            %td 1/29/13
            %td 1/31/13
            %td 3/4/13
            %td UNX82L
          %tr
            %td
            %td
            %td
            %td
            %td
            %td
            %td
          %tr
            %td
            %td
            %td
            %td
            %td
            %td
            %td

obi-frontend-mobile-page/app/views/mypasses/tabtest.html.erb
<div id="usual1" class="usual">
  <ul>
    <li><a href="#tab1" class="selected">one</a></li>
    <li><a href="#tab2">two</a></li>
    <li><a href="#tab3">Tab 3</a></li>
  </ul>
  <div id="tab1">This is tab 1.</div>
  <div id="tab2">More content in tab 2.</div>
  <div id="tab3">Tab 3 is always last!</div>
</div>

obi-frontend-mobile-page/app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

obi-frontend-mobile-page/app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

obi-frontend-mobile-page/app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Name
    %th Title
    %th Description
    %th Image
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.name
      %td= post.title
      %td= post.description
      %td= post.image
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

obi-frontend-mobile-page/app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

obi-frontend-mobile-page/app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @post.name
%p
  %b Title:
  = @post.title
%p
  %b Description:
  = @post.description
%p
  %b Image:
  = @post.image

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

obi-frontend-mobile-page/app/views/static_pages/checkout.html.haml
.row.account-info
  .row
    .span5.timeline.offset4
      .icon.first.active
      .border.first.active
      .icon.second.active
      .border.second
      .icon.third
  %p.page-title
    CHECKOUT
  %small.label-comment you have selected:
  .row.checkout-box
    .row
      .span3
        %p PASS
      .span3
        %p LOCATION
      .span3
        %p PRICE
      .span3
        %p REMOVE
    .span13.checkout-info-box
      .span3.first-item
        .control-group
          .controls
            =image_tag('product.jpg')
        .control-group
          .controls
            %a{:href => "#"} Change Selection
      .span3.second-item
        .control-group
          .controls
            %p New Youk Health
        .control-group
          .controls
            %p and Racquet
        .control-group
          .controls
            %p 123 Street
        .control-group
          .controls
            %p City, ST 00000
        .control-group
          .controls
            %p (XXX)XXX-XXXX
      .span3.third-item
        .control-group
          .controls
            %p $15
      .span3.fourth-item
        .control-group
          .controls
            %p X
  .row.account-box
    .row
      %p.container-title ACCOUNT INFO
    .span13.control-box
      .span4
        .control-group
          .controls
            %input#first-name{:placeholder => "first name", :type => "text"}/
        .control-group
          .controls
            %input#password{:placeholder => "password", :type => "password"}/
      .span4
        .control-group
          .controls
            %input#last-name{:placeholder => "last name", :type => "text"}
        .control-group
          .controls
            %input#password-confirm{:placeholder => "confirm password", :type => "password"}
      .span4
        .control-group
          .controls
            %input#email-address{ :placeholder => "email address", :type => "email" }
  .row.account-box
    .row
      %p.container-title BILLING ADDRESS
    .span13.control-box.billing-control-box
      .span8
        .control-group
          .controls
            %input#address1-name{:placeholder => "address 1", :type => "text"}/
        .control-group
          .controls
            %input#address2-field{:placeholder => "address 2 (apt, suit, unit)", :type => "text"}/
      .span4
        .control-group
          .row
            .span2
              %input#city-name{:placeholder => "city", :type => "text"}/
            .span1
              .custom-select
                .select-arrow
                %select
                  %option ST
                  %option US
        .control-group
          .controls
            %input#zipcode-field{:placeholder => "zipcode", :type => "text"}
  .row.account-box
    .row
      %p.container-title CREDIT CARD INFO
    .span13.control-box.credit-card-info-box
      .row
        .span8
          .control-group
            .controls
              %input#full-name{:placeholder => "name on card", :type => "text"}/
          .control-group
            .controls
              %input#phone-number{:placeholder => "**** **** **** 3182", :type => "text"}/
        .span4
          .control-group
            .row
              .span2
                %label EXP. DATE
              .span1
                .custom-select
                  .select-arrow
                  %select
                    %option 00
                    %option 01
                    %option 02
                    %option 03
                    %option 04
                    %option 05
              .span1{:style=>"width:10px;"}
                %label{:style => "width:10px"} /
              .span1
                .custom-select
                  .select-arrow
                  %select
                    %option 00
                    %option 01
                    %option 02
                    %option 03
                    %option 04
                    %option 05
          .control-group
            .controls
              %input#cvv-field{:placeholder => "cvv", :type => "text"}
      .row
        .span8
          .control-group
            .controls
              %label.checkbox
                %input{:type => "checkbox"}/
                save this card

  .row.last-row.checkout-box-control
    .span3.offset9
      %button.btn.btn-success{:type => "button"} PURCHASE PASS

obi-frontend-mobile-page/app/views/static_pages/choosepass.html.haml
.container
  .choosepass
    .timeline.clearfix
      .icon.active
      .border.active
      .icon.second.active
      .border
      .icon.third

    .checkout-inner
      %h1="Checkout"
      %h4="You have selected"
      .mainitems.clearfix
        .heading-txt
          Pass
        .heading-txt
          Location
        .heading-txt
          Price
        .heading-txt
          Remove
        .mainItems-inner.clearfix
          .itemRow.first
            =image_tag('product.jpg')
            %a{:href => "#"}
              Change Selection
          .itemRow
            .location-txt
              New York Health
              and Racquet
              123 Street
              City, ST 00000
              (XXX)XXX-XXXX
          .itemRow
            .price-txt
              $15
          .itemRow
            .remove-item
              X
    .form-tabs.clearfix
      .single-tab
        %h3 Account info
        .tabborder.clearfix
          %input{:type => "text", :name => "fname", :placeholder => "First Name", :class => "input-checkout"}
          %input{:type => "text", :name => "lname", :placeholder => "Last Name", :class => "input-checkout"}
          %input{:type => "text", :name => "email", :placeholder => "E-mail address", :class => "input-checkout last"}
          %input{:type => "password", :name => "password", :placeholder => "Password", :class => "input-checkout"}
          %input{:type => "password", :name => "cpassword", :placeholder => "Confirm Password", :class => "input-checkout"}
      .single-tab
        %h3 BILLING ADDRESS
        .tabborder.clearfix
          %input{:type => "text", :name => "address-1", :placeholder => "address 1", :class => "input-checkout large"}
          %input{:type => "text", :name => "lname", :placeholder => "city", :class => "input-checkout small"}
          .custom-select
            .select-arrow
            %select
              %option ST
              %option NY
              %option CA
          %input{:type => "text", :name => "address-2", :placeholder => "address 2 (apt, suit, unit)", :class => "input-checkout large"}
          %input{:type => "text", :name => "zip", :placeholder => "Zip Code", :class => "input-checkout"}
        .single-tab
          %h3 CREDIT CARD INFO
          .tabborder.clearfix
            %input{:type => "text", :name => "creditcard-name", :placeholder => "name on card", :class => "input-checkout large"}
            %label.exp-date EXP. DATE
            .custom-select
              .select-arrow
              %select
                %option 00
                %option 01
                %option 02
                %option 03
                %option 04
                %option 05
            .custom-select
              .select-arrow
              %select
                %option 00
                %option 01
                %option 02
                %option 03
                %option 04
                %option 05
            %input{:type => "text", :name => "creditcard-number", :placeholder => "card number", :class => "input-checkout large"}
            %input{:type => "text", :name => "cvv", :placeholder => "CVV", :class => "input-checkout"}

        %input{:type => "submit", :name => "checkout", :class => "submit-checkout", :value => "Purchase"}

obi-frontend-mobile-page/app/views/static_pages/findgym.html.haml
.row.find-gym-page
  .row
    .span5.timeline.offset4
      .icon.first.active
      .border.first.active
      .icon.second.active
      .border.second
      .icon.third
  %p.page-title
    FIND A GYM
  .row.find-gym-box
    .row
      .span8
        .input-append
          %input#appendedInputButton.span2{:type => "text"}/
          %button.btn{:type => "button"} Go!
    .row
      .span13.control-box.billing-control-box
        .span6.find-result-box
          .row.find-item
            .span5
              .row
                %p New York Health and Racquet
              .row
                .span1.distance
                  %small.label-distance 0.2 miles
                .span4.star-icon
            .span1.arrow-right
              .icon-arrow-left
          .row.find-item
            .span5
              .row
                %p Crunch Fitness
              .row
                .span1.distance
                  %small.label-distance 0.2 miles
                .span4.star-icon
            .span1.arrow-right
              .icon-arrow-left
          .row.find-item
            .span5
              .row
                %p David Barton
              .row
                .span1.distance
                  %small.label-distance 0.3 miles
                .span4.star-icon
            .span1.arrow-right
              .icon-arrow-left
          .row.find-item
            .span5
              .row
                %p New Youk Sports Club
              .row
                .span1.distance
                  %small.label-distance 0.3 miles
                .span4.star-icon
            .span1.arrow-right
              .icon-arrow-left
          .row.find-item
            .span5
              .row
                %p Dolphin Fitness
              .row
                .span1.distance
                  %small.label-distance 0.3 miles
                .span4.star-icon
            .span1.arrow-right
              .icon-arrow-left
        .span6.map-box
          =image_tag('map-test.jpg')

obi-frontend-mobile-page/app/views/static_pages/gymaccount.html.haml
.row.gym-account-info
  %p.page-title GYM ACCOUNT
  .row.account-box
    .row
      %p.container-title GYM AND LOCATION INFO
    .span13.control-box
      .row.first-row
        .span4
          .control-group
            .controls
              %input#first-name{:placeholder => "Jogn", :type => "text"}/
        .span4
          .control-group
            .controls
              %input#last-name{:placeholder => "Doe", :type => "text"}
        .span4
          .control-group
            .controls
              %input#email-address{ :placeholder => "jdoe@email.com", :type => "email" }
      .row.second-row
        .span8
          .control-group
            .controls
              %input#street-name{:placeholder => "123 Street", :type => "text"}/
        .span4
          .control-group
            .row
              .span3
                %input#first-name{:placeholder => "City", :type => "text"}/
              .span1
                .custom-select
                  .select-arrow
                  %select
                    %option ST
                    %option US
      .row.third-row
        .span8
          .control-group
            .controls
              %input#street-name{:placeholder => "123 Street", :type => "text"}/
        .span4
          .control-group
            .controls
              %input#number-field{:placeholder => "12345", :type => "text"}
      .row.fourth-row
        .span4
          .control-group
            .controls
              %input#first-name{:placeholder => "Jogn", :type => "text"}/
        .span4
          .control-group
            .controls
              %input#last-name{:placeholder => "Doe", :type => "text"}
        .span4
          .control-group
            .controls
              %input#email-address{ :placeholder => "jdoe@email.com", :type => "email" }
    .row
      .span3.offset9
        %a{:href=>"#", :style=>"color: #034bd1;"} More than one locatin? Add another form
    .row
      .row
        %p.container-title AMENITIES
      .span13.control-box.amenities-controlbox
        .row.check-box-control
          .span3.first-col
            %label.checkbox
              %input{:type => "checkbox"}/
              towel service
            %label.checkbox
              %input{:type => "checkbox"}/
              lockers
            %label.checkbox
              %input{:type => "checkbox"}/
              group fitness
            %label.checkbox
              %input{:type => "checkbox"}/
              sauna/steam room
          .span3.second-col
            %label.checkbox
              %input{:type => "checkbox"}/
              pilates
            %label.checkbox
              %input{:type => "checkbox"}/
              mat area
            %label.checkbox
              %input{:type => "checkbox"}/
              retail
            %label.checkbox
              %input{:type => "checkbox"}/
              personal trainer
          .span3.third-col
            %label.checkbox
              %input{:type => "checkbox"}/
              ride studio
            %label.checkbox
              %input{:type => "checkbox"}/
              yoga
            %label.checkbox
              %input{:type => "checkbox"}/
              boxng ring
            %label.checkbox
              %input{:type => "checkbox"}/
              live DJs
          .span3.fourth-col
            %label.checkbox
              %input{:type => "checkbox"}/
              dotfit
            %label.checkbox
              %input{:type => "checkbox"}/
              pool
            %label.checkbox
              %input{:type => "checkbox"}/
              tanning bed
            %label.checkbox
              %input{:type => "checkbox"}/
              shwers
          .span3.fifth-col
            %label.checkbox
              %input{:type => "checkbox"}/
              free weights
            %label.checkbox
              %input{:type => "checkbox"}/
              parking
            %label.checkbox
              %input{:type => "checkbox"}/
              cafe
            %label.checkbox
              %input{:type => "checkbox"}/
              juice bar
    .row
      .row
        %p.container-title
      .span13.control-box.image-upload-box
        .span4.form-inline
          .input-append
            %input#appendedInputButton.span2{:type => "text"}/
            %button.btn{:type => "button"} UPLOAD
        .span4.form-inline
          .input-append
            %input#appendedInputButton.span2{:type => "text"}/
            %button.btn{:type => "button"} UPLOAD
        .span4.form-inline
          .input-append
            %input#appendedInputButton.span2{:type => "text"}/
            %button.btn{:type => "button"} UPLOAD
    .row
      .row
        .span2
          %p.container-title PRICING
        .span4
          %label.pricing-label Blurb about pricing
      .span13.pricing-box
        .span4.pricing-col
          .controls.controls-row
            .span1.img-box{:style=>"width:100px;"}
              =image_tag('one.png')
            .span1{:style=>"width:50px;"}
              %p{:style=>"font-size: 40px; margin-left: 20px; margin-top: 33px;"} $
            .span1{:style=>"margin-left: 0px;"}
              %input{:placeholder => "20", :type => "text"}
        .span4.pricing-col
          .controls.controls-row
            .span1.img-box{:style=>"width:100px;"}
              =image_tag('onemonth.png')
            .span1{:style=>"width:50px;"}
              %p{:style=>"font-size: 40px; margin-left: 20px; margin-top: 33px;"} $
            .span1{:style=>"margin-left: 0px;"}
              %input{:placeholder => "20", :type => "text"}
        .span4.pricing-col
          .controls.controls-row
            .span1.img-box{:style=>"width:100px;"}
              =image_tag('product.jpg')
            .span1{:style=>"width:50px;"}
              %p{:style=>"font-size: 40px; margin-left: 20px; margin-top: 33px;"} $
            .span1{:style=>"margin-left: 0px;"}
              %input{:placeholder => "20", :type => "text"}

    .row.account-box
      .row
        %p.container-title BANKING INFO
      .span13.control-box.banking-info-box
        .row
          .span8
            .control-group
              .controls
                %input#full-name{:placeholder => "name on card", :type => "text"}/
          .span4
            .control-group
              .row
                .span2
                  %label TYPE OF ACCOUNT
                .span2
                  .custom-select
                    .select-arrow
                    %select
                      %option 00
                      %option 01
                      %option 02
                      %option 03
                      %option 04
                      %option 05
        .row
          .span6
            .control-group
              .controls
                %input#phone-number{:placeholder => "0000000", :type => "text"}/
          .span6
            .control-group
              .controls
                %input#cvv-field{:placeholder => "0000000", :type => "text"}
  .row.last-row.gym-checkout-box-control
    .span2.offset8
      %button.btn{:type => "button"} CANCEL
    .span2
      %button.btn.btn-success{:type => "button"} SAVE

obi-frontend-mobile-page/app/views/static_pages/home.html.haml
%ul.test-page
  %li=link_to('>> CHECKOUT', checkout_path)
  %li=link_to('>> RETURNINGUSER', returninguser_path)
  %li=link_to('>> MY ACCOUNT', myaccount_path)
  %li=link_to('>> MY PASS', mypasses_path)
  %li=link_to('>> GO WORKOUT!', go_work_out_path)
  %li=link_to('>> FIND A GYM', findgym_path)
  %li=link_to('>> GYM ACCOUNT', gymaccount_path)
  %li=link_to('>> HOME PAGE', index_path)

  %li=link_to('>> MOBILE PAGES', mobile_home_path)

obi-frontend-mobile-page/app/views/static_pages/index.html.haml
.row.home-page
  .row.banner
    .nav-bar.links
      %ul
        %li
          %a{:href => "/contact"} GYM MANAGER
        %li
          %a{:href => "/faq"} SIGN IN
    .row.inner-main
      #sign-in-box.span2{:style=>"float:right;margin-right:10px;"}
        %form.form-horizontal{:action => "#", :type => "POST"}
          .row
            %input#inputEmail{:placeholder => "user name", :type => "text"}/
          .row
            %input#inputPassword{:placeholder => "password", :type => "password"}/
          .row
            %label.checkbox
              %input{:type => "checkbox", :style=>"width:10px;margin-left:-13px"}/
              Remember me
          .row
            .span2{:style=>"margin-left:5px;width:70px;"}
              %label Sign in with
            .span1{:style=>"margin-left:0px;width:50px;"}
              =link_to(image_tag('f.png'),"#")
              =link_to(image_tag('t.png'),"#")
          .row
            %input{:type => "submit", :value => "SIGN IN", :style=>"margin-left: 5px;"}/

    .row.logo-box
      .logo
        %h1 #{ link_to 'pop in gym!', '#'}
        %h3 short-term gym passes on-the-go
    .row.sign-controll-box
      %form.form-horizontal{:action => "#", :type => "POST"}
        .row
          .span2{:style=>"margin-left:180px;"}
            %label{:style=>"font-size: 30px; float: right; margin-top: 6px;"} SIGN UP
          .span5{:style=>"margin-left:0px;"}
            %input{:type=>"email",:placeholder=>"email address"}
          .span1{:style=>"margin-left:14px;"}
            %input{:type=>"submit",:value=>"GET START"}
        .row
          .span2.offset5
            %label{:style=>"float:right;"} Or sign up with
          .span1
            =link_to(image_tag('f.png'),"#")
            =link_to(image_tag('t.png'),"#")
  .row.homepage-controls
    .span3.col{:style=>"margin-left:170px;"}
      %a{:href => "#"}
        =image_tag('find-gym.png')
        %p Find the nearest gym with the amenities you want.
    .span3.col
      %a{:href => "#"}
        =image_tag('choose-pass.png')
        %p Buy the pass that best suits your needs: 1-day, 4-day, or 1-month.
    .span3.col
      %a{:href => "#"}
        =image_tag('go-workout.png')
        %p Redeem your pass and go workout!